[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
# link.x is provided by cortex-m-rt and pulls in your memory.x.
rustflags = ["-C", "link-arg=-Tlink.x"]
